###
GET /rest/caregiver/joinCaregiver

###
POST http://localhost:80/rest/caregiver/caregiverExcel

###
GET http://localhost:8080/api/members/bad
Accept: application/json

###
GET http://localhost:8080/api/members/user-ex
Accept: application/json

###
GET http://localhost:8080/api/members/user-ex
Accept: text/html