###
GET /rest/caregiver/joinCaregiver

###
POST http://localhost:80/rest/caregiver/caregiverExcel

###
GET http://localhost:8080/api/members/bad
Accept: application/json

###
GET http://localhost:8080/api/members/user-ex
Accept: application/json

###
GET http://localhost:8080/api/members/user-ex
Accept: text/html


###
GET http://localhost:8080/api/response-status-ex1
Accept: application/json


###
GET http://localhost:8080/api/response-status-ex2
Accept: application/json

###
GET http://localhost:8080/api/default-handler-ex?data=qqq
Accept: application/json

###
GET http://localhost:8080/api2/members/bad
Accept: application/json

###
GET http://localhost:8080/api2/members/user-ex
Accept: application/json

###
GET http://localhost:8080/api2/members/ex
Accept: application/json